name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/vectors/objects_x2.svg
  - assets/vectors/cellular_connection_7_x2.svg
  - assets/vectors/battery_13_x2.svg
  - assets/vectors/wifi_14_x2.svg
  - assets/images/rectangle_1.png
  - assets/vectors/iedit_x2.svg
  - assets/vectors/bmeeting_x2.svg
  - assets/vectors/home_5_x2.svg
  - assets/vectors/wifi_16_x2.svg
  - assets/vectors/cellular_connection_x2.svg
  - assets/vectors/group_x2.svg
  - assets/vectors/user_1_x2.svg
  - assets/vectors/battery_x2.svg
  - assets/vectors/arrow_left_11_x2.svg
  - assets/vectors/calendar_1_x2.svg
  - assets/images/image.jpeg
  - assets/images/image_1.jpeg
  - assets/vectors/wifi_3_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/alarm_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/apple_x2.svg
  - assets/vectors/microphone_x2.svg
  - assets/vectors/cellular_connection_18_x2.svg
  - assets/vectors/share_x2.svg
  - assets/vectors/fadd_2_x2.svg
  - assets/vectors/arrow_left_7_x2.svg
  - assets/vectors/battery_7_x2.svg
  - assets/vectors/camping_lantern_x2.svg
  - assets/vectors/send_3_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/image_4_x2.svg
  - assets/vectors/mail_1_x2.svg
  - assets/vectors/lock_x2.svg
  - assets/vectors/send_x2.svg
  - assets/vectors/profile_x2.svg
  - assets/vectors/lock_1_x2.svg
  - assets/vectors/arrow_right_1_x2.svg
  - assets/vectors/battery_5_x2.svg
  - assets/vectors/wifi_9_x2.svg
  - assets/vectors/cellular_connection_10_x2.svg
  - assets/vectors/arrow_left_3_x2.svg
  - assets/images/unsplash_yo_1_cwjvkfy.jpeg
  - assets/vectors/battery_10_x2.svg
  - assets/vectors/cellular_connection_12_x2.svg
  - assets/vectors/wifi_2_x2.svg
  - assets/vectors/arrow_right_x2.svg
  - assets/vectors/eremove_x2.svg
  - assets/images/image_18.jpeg
  - assets/images/container_27.jpeg
  - assets/images/rectangle_1.png
  - assets/vectors/wifi_18_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/arrow_left_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/aadd_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/cellular_connection_3_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/search_6_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/battery_11_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/images/image_3.jpeg
  - assets/vectors/alocation_x2.svg
  - assets/vectors/search_2_x2.svg
  - assets/vectors/cellular_connection_17_x2.svg
  - assets/vectors/battery_20_x2.svg
  - assets/vectors/arrow_left_9_x2.svg
  - assets/vectors/wifi_15_x2.svg
  - assets/vectors/logout_x2.svg
  - assets/vectors/home_1_x2.svg
  - assets/vectors/compare_x2.svg
  - assets/vectors/calendar_3_x2.svg
  - assets/vectors/settings_gear_2_x2.svg
  - assets/vectors/search_9_x2.svg
  - assets/vectors/search_4_x2.svg
  - assets/vectors/send_4_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/arrow_left_13_x2.svg
  - assets/vectors/wifi_10_x2.svg
  - assets/vectors/user_3_x2.svg
  - assets/vectors/alien_29_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/line_4_x2.svg
  - assets/vectors/line_1_x2.svg
  - assets/vectors/mail_x2.svg
  - assets/vectors/line_5_x2.svg
  - assets/vectors/bullet_list_67_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/home_x2.svg
  - assets/vectors/user_x2.svg
  - assets/vectors/line_2_x2.svg
  - assets/vectors/battery_16_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/line_3_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/resizing_handle_2_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/cellular_connection_6_x2.svg
  - assets/vectors/home_3_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/battery_19_x2.svg
  - assets/vectors/arrow_left_1_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/responsive_x2.svg
  - assets/vectors/vector_64_x2.svg
  - assets/vectors/wifi_8_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/circle_in_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/cellular_connection_9_x2.svg
  - assets/vectors/user_2_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/resizing_handle_1_x2.svg
  - assets/vectors/cellular_connection_19_x2.svg
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/wifi_13_x2.svg
  - assets/vectors/resizing_handle_x2.svg
  - assets/vectors/cellular_connection_1_x2.svg
  - assets/vectors/battery_1_x2.svg
  - assets/vectors/lock_2_x2.svg
  - assets/vectors/battery_8_x2.svg
  - assets/vectors/resizing_handle_3_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/battery_6_x2.svg
  - assets/vectors/wifi_5_x2.svg
  - assets/vectors/cellular_connection_11_x2.svg
  - assets/vectors/arrow_left_12_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/images/rectangle_1.png
  - assets/images/image_135.jpeg
  - assets/vectors/battery_18_x2.svg
  - assets/vectors/cellular_connection_20_x2.svg
  - assets/vectors/aadd_1_x2.svg
  - assets/vectors/search_7_x2.svg
  - assets/vectors/wifi_17_x2.svg
  - assets/vectors/bell_4_x2.svg
  - assets/vectors/arrow_left_10_x2.svg
  - assets/images/image_2.jpeg
  - assets/vectors/wifi_20_x2.svg
  - assets/vectors/search_8_x2.svg
  - assets/vectors/arrow_left_6_x2.svg
  - assets/vectors/aadd_3_x2.svg
  - assets/vectors/atime_x2.svg
  - assets/vectors/battery_4_x2.svg
  - assets/vectors/calendar_2_x2.svg
  - assets/vectors/aadd_2_x2.svg
  - assets/vectors/search_3_x2.svg
  - assets/vectors/cellular_connection_2_x2.svg
  - assets/images/rectangle_1.png
  - assets/images/rectangle.jpeg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/wifi_11_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/fchat_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/cellular_connection_8_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/battery_17_x2.svg
  - assets/vectors/arrow_left_8_x2.svg
  - assets/vectors/handshake_x2.svg
  - assets/images/rectangle_1.png
  - assets/vectors/wifi_19_x2.svg
  - assets/vectors/calendar_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/send_2_x2.svg
  - assets/vectors/image_6_x2.svg
  - assets/vectors/cellular_connection_14_x2.svg
  - assets/vectors/arrow_left_5_x2.svg
  - assets/vectors/battery_14_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/settings_gear_3_x2.svg
  - assets/vectors/microphone_2_x2.svg
  - assets/vectors/fadd_1_x2.svg
  - assets/images/image_1355.jpeg
  - assets/vectors/settings_gear_x2.svg
  - assets/vectors/battery_2_x2.svg
  - assets/vectors/arrow_left_4_x2.svg
  - assets/vectors/wifi_7_x2.svg
  - assets/vectors/cellular_connection_15_x2.svg
  - assets/vectors/bell_x2.svg
  - assets/vectors/home_2_x2.svg
  - assets/vectors/search_5_x2.svg
  - assets/vectors/bmeeting_2_x2.svg
  - assets/vectors/profile_1_x2.svg
  - assets/images/rectangle_1.png
  - assets/images/image_136.jpeg
  - assets/images/image_1354.jpeg
  - assets/vectors/notifications_15_x2.svg
  - assets/vectors/bell_3_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/battery_9_x2.svg
  - assets/vectors/search_1_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/group_3_x2.svg
  - assets/vectors/cellular_connection_16_x2.svg
  - assets/vectors/wifi_12_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/notifications_151_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/images/image_1352.jpeg
  - assets/images/rectangle_1.png
  - assets/images/image_1351.png
  - assets/images/image_1353.png
  - assets/vectors/home_4_x2.svg
  - assets/vectors/calendar_date_1_x2.svg
  - assets/vectors/bxmap_x2.svg
  - assets/vectors/bmeeting_3_x2.svg
  - assets/vectors/battery_15_x2.svg
  - assets/vectors/settings_gear_1_x2.svg
  - assets/vectors/wifi_4_x2.svg
  - assets/vectors/bell_1_x2.svg
  - assets/vectors/settings_gear_5_x2.svg
  - assets/vectors/home_6_x2.svg
  - assets/vectors/calendar_date_x2.svg
  - assets/vectors/search_10_x2.svg
  - assets/vectors/cellular_connection_13_x2.svg
  - assets/vectors/bmeeting_1_x2.svg
  - assets/vectors/bell_2_x2.svg
  - assets/vectors/group_2_x2.svg
  - assets/vectors/group_4_x2.svg
  - assets/images/image_20.jpeg
  - assets/vectors/cellular_connection_5_x2.svg
  - assets/vectors/send_1_x2.svg
  - assets/vectors/arrow_left_2_x2.svg
  - assets/vectors/image_5_x2.svg
  - assets/vectors/battery_12_x2.svg
  - assets/vectors/microphone_1_x2.svg
  - assets/vectors/wifi_6_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/settings_gear_4_x2.svg
  - assets/vectors/fadd_x2.svg
  - assets/vectors/badd_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/search_x2.svg

